spring.application.name=servico-de-pdf

server.port=8080

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.mvc.pathmatch.matching-strategy=ant_path_matcher